import Head from 'next/head'
import Navbar from './navbar'
import Welcome from './welcome'
import About from './about'
import Projects from './projects'
import Contact from './contact'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Kara Huynh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Welcome/>
      <About/>
      <Projects />
      <Contact />


      {/* <footer className="">
        <h1 className="">
          made with love
        </h1>
      </footer> */}
    </div>
  )
}
