import Head from 'next/head'
import Navbar from './navbar'
import Welcome from './welcome'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Kara Huynh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Welcome/>

      <main className="">
        
      </main>

      {/* <footer className="">
        <h1 className="">
          made with love
        </h1>
      </footer> */}
    </div>
  )
}
